import React from 'react'

const privacypol = () => {

  return (
    <div className="h-auto px-[4vw] py-14 w-screen flex flex-col items-start privacy">
        <h1 className='uppercase whitespace-nowrap'>privacy policy</h1>
        <h3>Introduction</h3>
        <p>Welcome to Fugin Guides. Your privacy is important to us. This privacy policy explains what personal data we collect, how we use it, and how we protect it.</p>
        <h3>Information Collection</h3>
        <p>We collect personal data that you provide to us when you contact us through our contact form. This may include your name and email address.</p>
        <h3>Use of Information</h3>
        <p>We use the information we collect to respond to your inquiries and to improve our services. We do not sell or share your personal data with third parties.</p>
        <h3>Google AdSense</h3>
        <p>We use Google AdSense to display ads on our website. Google may collect and use data for ad personalization and performance measurement. For more information about how Google collects and uses data, please visit Google’s Privacy Policy.

You can opt out of personalized advertising by visiting Google’s Ad Settings.</p>
<h3>Use of Google Analytics</h3>
<p>Our website uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.

Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf.

By using our website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.

For more information on Google Analytics, including how to opt-out, please visit Google Analytics Privacy Overview.</p>
        <h3>Data Security</h3>
        <p>We take reasonable measures to protect your personal data from unauthorized access or disclosure. However, no method of transmission over the internet or electronic storage is completely secure.</p>
        <h3>User Rights</h3>
        <p>You have the right to access, correct, or delete your personal data. If you wish to exercise these rights, please contact us at fuginguides@gmail.com.</p>
        <h3>Changes to This Privacy Policy</h3>
        <p>We may update this privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page.</p>
        <h3>Contact Information</h3>
        <p>If you have any questions about this privacy policy, please contact us at  fuginguides@gmail.com.</p>
        <h3>Last updated: </h3>
        <p>31/07/2024</p>

    </div>
  )
}

export default privacypol